---
image: ubuntu:24.04

stages:
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  fennel: 1.5.1

.install_fennel: &fennel |-
  cd "$HOME"
  git clone -q --depth=1 --branch="$fennel" \
        https://git.sr.ht/~technomancy/fennel
  cd fennel || exit -1
  make install
  cd "$CI_PROJECT_DIR"

.install_deps: &deps |-
  cd "$HOME"
  git clone -q --depth=1 --branch="main" \
        https://gitlab.com/andreyorst/deps.fnl
  cd deps.fnl || exit -1
  chmod 755 deps
  mkdir -p /usr/local/bin/
  cp deps /usr/local/bin/
  cd "$CI_PROJECT_DIR"

.prepare: &prepare
  - apt-get -yq update
  - >
    apt-get -qq install -yq
    $LUA lib${LUA}-dev luarocks
    git make gcc
  - *fennel
  - *deps

Lua5.2:
  stage: test
  before_script:
    - export LUA=lua5.2
    - *prepare
  script:
    - deps --lua $LUA --merge dev-deps.fnl tasks/run-tests

Lua5.3:
  stage: test
  before_script:
    - export LUA=lua5.3
    - *prepare
  script:
    - deps --lua $LUA --merge dev-deps.fnl tasks/run-tests

Lua5.4:
  stage: test
  before_script:
    - export LUA=lua5.4
    - *prepare
  script:
    - deps --lua $LUA --merge dev-deps.fnl tasks/run-tests
